Add: FPC 0.5mm pitch top and bottom connector JLC parts numbers
BerkeleyHCI/PolymorphicBlocks pull request #378
Opened 2024-09-20 07:59 UTC by Suke0811

This should cover most of the popular P0.5 fpc sizes. FCC and FCA are just different packages.

2024-09-20 08:04 UTC, Suke0811 commented
Change the footprint to TE connectors that are closer to the AF07 in the future once tested.

2024-09-20 20:03 UTC, ducky64 requested changes
Style improvement suggestions.

Can you also make sure both part number format strings include an asterisk for the packaging,?

2024-09-20 20:03 UTC, ducky64 commented on edg/parts/PassiveConnector_Fpc.py
> +    # 5: 'C262578',
```suggestion
    5: 'C262230',  # also C262578 in different packaging
```
maybe condense into one line (and below instances)

2024-09-21 00:11 UTC, ducky64 commented
Also we can change the footprint in a separate PR. I'm planning to run a separate test panel that includes the footprint test.

2024-09-21 01:59 UTC, Suke0811 commented on edg/parts/PassiveConnector_Fpc.py
>      self.assign(self.lcsc_part, self.PART_NUMBERS[length])
```
f"AFC01-S{length:02d}FC*-00"
f"AFC07-S{length:02d}EC*-00"
```

2024-09-21 02:29 UTC, Suke0811 commented on edg/parts/PassiveConnector_Fpc.py
> +    7: '',  # 46
Added the missing 7 pos parts number

2024-09-21 02:31 UTC, Suke0811 commented
How's this change[edae225](https://github.com/BerkeleyHCI/PolymorphicBlocks/pull/378/commits/edae22598e4da5acb22e49088752961e9b68043c)?

2024-09-21 04:26 UTC, ducky64 approved these changes

2024-09-21 04:26 UTC, merged